Aks cluster: Devicekubercluster
apiVersion: v1
	kind: Service
	metadata:
	    name: Devicekubercluster
	spec:
	    type: LoadBalancer
	    ports:
	    - port: 80 
	    selector:
	        app: Devicekubercluster
